import strings from "translation";

export const BASICAMOUNTLABEL = strings["HEADER.BASICAMOUNTLABEL"];
export const DAPERCENTAGELABEL = strings["HEADER.DAPERCENTAGELABEL"];
export const HRAPERCENTAGELABEL = strings["HEADER.HRAPERCENTAGELABEL"];
export const CANPERCENTAGELABEL = strings["HEADER.CANPERCENTAGELABEL"];
export const STATUSLABEL = strings["HEADER.STATUSLABEL"];
export const EFFECTDATELABEL = strings["HEADER.EFFECTDATELABEL"];
export const TBLHEAD = strings["HEADER.TBLHEAD"];
export const UPCOMINGREVISE = strings["HEADER.wage.upcoming.revise"];
export const ADDNEWWAGE = strings["HEADER.ADDNEWWAGE"];
export const HOMEPATH = strings["HEADER.HOMEPATH"];
export const CURRENTPATH = strings["HEADER.CURRENTPATH"];

export const STATUSCHANGEHEAD = strings["STATUS.CHANGE.PERMISSION.HEADING"];
export const STATUSCHANGESUBHEAD = strings["STATUS.CHANGE.PERMISSION.SUBHEADING"];
export const STATUSCHANGEPERMISSIONYES = strings["STATUS.CHANGE.PERMISSION.YES"];
export const STATUSCHANGEPERMISSIONNO = strings["STATUS.CHANGE.PERMISSION.NO"];
export const STATUSCHANGEDELETED = strings["STATUS.CHANGE.DELETED"];
export const STATUSDELETEDSUBHEAD = strings["STATUS.CHANGE.DELETED.SUBHEAD"];
export const STATUSDELETEDSUCCESS = strings["STATUS.CHANGE.DELETED.SUCCESS"];
export const STATUSDELETEDSCANCEL = strings["STATUS.CHANGE.CANCELLED"];
export const STATUSDELETEDSCANCELSHEAD = strings["STATUS.CHANGE.CANCELLED"];
export const STATUSDELETEDSCANCELERROR = strings["STATUS.CHANGE.CANCELLED.ERROR"];







